# Generated by Django 2.1.7 on 2021-05-16 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210516_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 16, 20, 31, 16, 299627)),
        ),
    ]
